[package]
name = "rprch"
version = "0.5.0"
authors = ["Serbe <mkoctuk@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
dotenv = "0.13"
postgres = "0.15" 
r2d2 = "0.8"
r2d2_postgres = "0.14"